[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list

ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list

ruleset=🤖 ChatGPT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🤖 ChatGPT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list

ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list

ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list

ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list

ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list

ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list

ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list

ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list

ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

ruleset=🐟 漏网之鱼,[]FINAL
;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🇹🇼 台湾自动`[]🚀 手动切换

custom_proxy_group=🚀 手动切换`select`.*

custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🤖 ChatGPT`select`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🚀 节点选择

custom_proxy_group=📲 电报消息`select`[]🇭🇰 香港自动`[]🇸🇬 新加坡自动`[]🚀 节点选择

custom_proxy_group=📹 油管视频`select`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动

custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇺🇲 美国自动

custom_proxy_group=🌍 国外媒体`select`[]🇭🇰 香港自动`[]🇯🇵 日本自动`[]🇺🇲 美国自动

custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🇭🇰 香港自动

custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🇭🇰 香港自动

custom_proxy_group=Ⓜ️ 微软Bing`select`[]🇺🇲 美国自动

custom_proxy_group=🍎 苹果服务`select`[]DIRECT

custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🇭🇰 香港自动

custom_proxy_group=🎶 网易音乐`select`[]DIRECT

custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🇭🇰 香港自动

custom_proxy_group=🎯 全球直连`select`[]DIRECT

custom_proxy_group=🛑 广告拦截`select`[]REJECT

custom_proxy_group=🍃 应用净化`select`[]REJECT

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]DIRECT

custom_proxy_group=🇭🇰 香港自动`url-test`(香港|HK|hgc|hkt|hkbn|icable|G口)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇹🇼 台湾自动`url-test`(台湾|TW|hinet)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇯🇵 日本自动`url-test`(日本|东京|JP|gmo|aws|sakura)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇸🇬 新加坡自动`url-test`(新加坡|SG|Singapore|狮城)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🇺🇲 美国自动`url-test`(美国|US|9929|chatgpt|洛杉矶|cera)`http://www.gstatic.com/generate_204`300,,100

custom_proxy_group=🎥 奈飞节点`url-test`(NF|奈飞|Netflix|NETFLIX)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
